#!/bin/bash

if [ "$#" -gt 0 ] # Need arguments for git commit
then # Can work on stuff
	# Saves me some typing
	read -p "Enter the commit description: " commsg # Prompt me for a commit description
	read -p "Enter the names of the files to be committed, separated by spaces (wildcards are supported): " comfiles # Prompt for the files to be commmitted
	git commit -m "$commsg" $comfiles # Commit the files with the given message

else # Wrong number of arguments
	echo Usage: `basename "$0"`: file{1,2,...,n}
fi
