#!/bin/bash

if [ "$#" = 1 ] # User has entered a branch name
then 
	git push origin "$1" # Push to the branch specified in the arguments

elif [ -n "$CURBRANCH" ] # The user has defined the environment variable CURBRANCH
then
	git push origin "$CURBRANCH" # Push to it

else # Error
	echo Usage: `basename "$0"` \[branchName\]
	echo You may also define the environment variable CURBRANCH in Git Bash as follows: \"export CURBRANCH=branchName\"
	echo An argument takes precedence over the environment variable
fi
